parameters:
# the parameter name is an arbitrary string (the 'app.' prefix is recommended
    env(APP_DOCUMENT_INDEX_COUNT_BATCH): "100"

    app.log_path: '%env(APP_LOG_PATH)%'
    app.log_file: '%env(APP_LOG_FILE)%'
    app.document_index.count_batch: '%env(APP_DOCUMENT_INDEX_COUNT_BATCH)%'
