version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./var/log/access:/var/log/access
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=false
      #- node.name=es_node1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
    ports:
      - "9200:9200"
    volumes:
      - ./var/elastic-data:/usr/share/elasticsearch/data
